/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/layouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/layouts` — list all layouts (role: read). */
        get: operations["list_layouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A `202 Accepted` body returned for an asynchronously-applied command. */
        AcceptedBody: {
            /** @description The command kind (e.g. `start`). */
            kind: string;
            /**
             * @description The operation id correlating this command's eventual outcome on the
             *     realtime stream.
             */
            operation_id: string;
        };
        /**
         * @description A persisted layout resource.
         *
         *     The `body` is the opaque, validated layout document the editor produces; the
         *     control plane stores and version-stamps it without interpreting its
         *     internals here. (Engine-side validation against `multiview-config` happens
         *     before a layout is applied.)
         */
        Layout: {
            /** @description The opaque layout document (canvas + cells), as canonical JSON. */
            body: unknown;
            /** @description Stable resource id. */
            id: string;
            /** @description Human-friendly name. */
            name: string;
        };
        /**
         * @description The fields a create/update accepts (the id is supplied separately on create
         *     and immutable on update).
         */
        LayoutInput: {
            /** @description The opaque layout document. */
            body: unknown;
            /** @description Human-friendly name. */
            name: string;
        };
        /**
         * @description A correlation id for an asynchronously-applied control command.
         *
         *     Returned to the client in a `202 Accepted` response and echoed by the engine
         *     on the realtime stream (`corr`) when the command's outcome is known.
         */
        OperationId: string;
        /**
         * @description An RFC 9457 problem-details document.
         *
         *     Serialized as `application/problem+json`. The `status` field is authoritative
         *     and is also used as the HTTP status code by the [`IntoResponse`] impl. A
         *     `status` outside the valid `100..=599` range falls back to `500`.
         */
        Problem: {
            /** @description A human-readable explanation specific to this occurrence. */
            detail?: string | null;
            /**
             * @description A URI reference identifying this specific occurrence (e.g. the request
             *     path or an operation id).
             */
            instance?: string | null;
            /**
             * Format: int32
             * @description The HTTP status code, duplicated into the body per RFC 9457.
             */
            status: number;
            /** @description A short, human-readable summary of the problem type. */
            title: string;
            /** @description A URI reference identifying the problem type (here a `/problems/<slug>`). */
            type: string;
        };
        /**
         * @description A coarse role governing which actions a principal may perform.
         *
         *     Ordered by privilege: `Viewer < Operator < Admin`. [`Role::can`] expresses
         *     the action gate.
         * @enum {string}
         */
        Role: "viewer" | "operator" | "admin";
        /** @description The body of a `POST /commands/swap` request. */
        SwapRequest: {
            /** @description The new source/input id to bind. */
            source: string;
            /** @description The tile/cell id whose source binding changes. */
            tile: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_layouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All layouts, id-sorted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"][];
                };
            };
            /** @description Missing or invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Authenticated but not authorized to read. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
