//! Minimal **runtime-load** wrapper over the proprietary NDI® SDK.
//!
//! > NDI® is a registered trademark of **Vizrt NDI AB**. See
//! > [ADR-0008](../decisions/ADR-0008.md) and `docs/io/ndi.md`.
//!
//! ## Why this crate exists
//!
//! The NDI SDK is **proprietary and royalty-free — not open source**, and its
//! license forbids static vendoring. The usual binding (`grafton-ndi`) links
//! `libndi` and bindgens the SDK headers **at build time** and *panics if the
//! SDK is absent* — which would force the proprietary SDK on the whole build.
//!
//! ADR-0008 therefore mandates a **dynamic-load** path: locate the
//! operator-provided NDI runtime dylib at **run time**, `dlopen` it, resolve the
//! NDI 6 entry point **`NDIlib_v6_load`**, and read the returned function table.
//! Because nothing is linked at build time, the default build — and even an
//! `ndi`-feature build — compiles and links **without the SDK present**.
//!
//! ## Why it is its own crate
//!
//! `dlopen`/`dlsym` is raw FFI and needs `unsafe`. The workspace `forbid`s
//! `unsafe_code`, and a `forbid` can never be relaxed downstream. Isolating the
//! single `unsafe` boundary in this tiny leaf crate (exactly as
//! `multiview-ntpsys` / `multiview-i915pmu` do for their syscalls) lets the
//! consuming crate (`multiview-output`) stay `forbid(unsafe_code)`. This crate
//! is pulled in **only** by `multiview-output`'s off-by-default `ndi` feature, so
//! the default workspace build never links it and `cargo deny`
//! (`all-features = false`) never scans it.
//!
//! ## What is scaffolding vs live
//!
//! The **testable core** is fully exercised here without the SDK:
//! - [`default_search_paths`] / [`find_runtime`] — the platform path search.
//! - [`NdiRuntime::load`] — open + resolve, returning a typed [`NdiSysError`]
//!   (never a panic, never a block) when the runtime is **absent** or the entry
//!   point is **missing**.
//!
//! The **live** part — actually calling into the SDK function table to create a
//! sender and push frames — only runs on a host with a resolvable NDI runtime and
//! is therefore gated behind the live-only test in the consuming crate. The raw
//! function-table ABI is the SDK's; this crate keeps the table as an **opaque,
//! non-null pointer** ([`NdiApiTable`]) and never reproduces the proprietary
//! struct layout (that would be a form of vendoring).

use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use std::ptr::NonNull;

use libloading::Library;

/// The typed `NDIlib` v6 C ABI, generated by `bindgen` from the **licensed** SDK
/// header at build time under the off-by-default `bindings` feature (NDI-L1).
///
/// This is the only place the proprietary struct layout is reproduced, and only
/// behind the feature gate: it is **derived mechanically** from the real header
/// (never hand-fabricated, never the SDK vendored or committed — ADR-0008). The
/// blanket `allow`s below are inherent to `bindgen`-generated C bindings (raw
/// `extern "C"` fns, C naming, unions); they are confined to this generated
/// module — the rest of the crate stays under the workspace lint set.
#[cfg(feature = "bindings")]
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unsafe_code,
    missing_docs,
    clippy::all,
    clippy::pedantic,
    clippy::missing_safety_doc
)]
pub mod ffi {
    //! `bindgen`-generated NDIlib ABI (the `NDIlib_v6` function table + structs).
    include!(concat!(env!("OUT_DIR"), "/ndi_bindings.rs"));
}

/// The NDI 6 dynamic-load entry-point symbol, NUL-terminated for `dlsym`. NDI 6
/// uses **`NDIlib_v6_load`** (not the v5 symbol); it returns a pointer to the SDK
/// function table.
pub const NDI_LOAD_SYMBOL: &[u8] = b"NDIlib_v6_load\0";

/// The same entry-point symbol as a display string (no trailing NUL), for
/// operator-facing messages.
pub const NDI_LOAD_SYMBOL_NAME: &str = "NDIlib_v6_load";

/// Environment variable the official NDI runtime installer exports, pointing at
/// the directory that contains the runtime dylib. Honoured first in the search.
pub const NDI_RUNTIME_ENV: &str = "NDI_RUNTIME_DIR_V6";

/// Errors from resolving / loading the NDI runtime.
///
/// Every variant is a *reported* outcome — the runtime being absent is the
/// expected case on a default host, **not** a crash. Marked `#[non_exhaustive]`.
#[derive(Debug)]
#[non_exhaustive]
pub enum NdiSysError {
    /// No NDI runtime dylib was found on any search path. The capability is
    /// simply unavailable; the caller reports it, never crashes.
    RuntimeNotFound {
        /// The candidate paths that were probed, for an actionable message.
        searched: Vec<PathBuf>,
    },
    /// A candidate dylib was found but `dlopen` failed (wrong arch, unreadable,
    /// missing transitive dep, …). Carries the OS error text.
    OpenFailed {
        /// The dylib that failed to open.
        path: PathBuf,
        /// The underlying loader error message.
        detail: String,
    },
    /// The dylib opened but did not export the `NDIlib_v6_load` entry point — it
    /// is not an NDI 6 runtime.
    SymbolMissing {
        /// The dylib that lacked the entry point.
        path: PathBuf,
        /// The underlying loader error message.
        detail: String,
    },
    /// `NDIlib_v6_load()` was called but returned a null table pointer.
    NullApiTable,
}

impl std::fmt::Display for NdiSysError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::RuntimeNotFound { searched } => write!(
                f,
                "NDI runtime not found (searched {} path(s)); install the NDI 6 \
                 runtime or set {NDI_RUNTIME_ENV}",
                searched.len()
            ),
            Self::OpenFailed { path, detail } => {
                write!(
                    f,
                    "failed to dlopen NDI runtime {}: {detail}",
                    path.display()
                )
            }
            Self::SymbolMissing { path, detail } => write!(
                f,
                "NDI runtime {} is missing the {NDI_LOAD_SYMBOL_NAME} entry point: {detail}",
                path.display(),
            ),
            Self::NullApiTable => {
                write!(f, "NDIlib_v6_load() returned a null function table")
            }
        }
    }
}

impl std::error::Error for NdiSysError {}

/// The platform-specific base file names of the NDI 6 runtime dylib.
///
/// On Linux the runtime ships as `libndi.so.<major>`; macOS as `libndi.dylib`.
/// Multiview targets only Linux + macOS (no Windows — see CLAUDE.md "Platforms").
#[must_use]
pub fn runtime_dylib_names() -> &'static [&'static str] {
    #[cfg(target_os = "macos")]
    {
        &["libndi.dylib", "libndi.4.dylib"]
    }
    #[cfg(not(target_os = "macos"))]
    {
        // Linux: the SONAME is versioned (`.so.<major>`); probe the common ones
        // plus the unversioned dev symlink.
        &[
            // The NDI **Advanced** SDK ships its runtime as `libndi_advanced.so.6`
            // (same `NDIlib_v6_load` entry point); probe it first, then the
            // standard runtime names.
            "libndi_advanced.so.6",
            "libndi_advanced.so",
            "libndi.so.6",
            "libndi.so.5",
            "libndi.so",
            "libndi.so.4",
        ]
    }
}

/// The directories searched for the NDI runtime, most-specific first.
///
/// Order: the `NDI_RUNTIME_DIR_V6` env var (the installer's own variable), then
/// the conventional install prefixes for the platform. The list is *candidate
/// directories*; each is combined with each [`runtime_dylib_names`] entry by
/// [`find_runtime`]. Nothing is opened here.
#[must_use]
pub fn default_search_paths() -> Vec<PathBuf> {
    let mut dirs: Vec<PathBuf> = Vec::new();
    if let Some(dir) = std::env::var_os(NDI_RUNTIME_ENV) {
        dirs.push(PathBuf::from(dir));
    }
    #[cfg(target_os = "macos")]
    {
        dirs.push(PathBuf::from("/usr/local/lib"));
        dirs.push(PathBuf::from("/opt/homebrew/lib"));
        dirs.push(PathBuf::from("/Library/NDI SDK for Apple/lib/macOS"));
    }
    #[cfg(not(target_os = "macos"))]
    {
        dirs.push(PathBuf::from("/usr/lib"));
        dirs.push(PathBuf::from("/usr/local/lib"));
        dirs.push(PathBuf::from("/usr/lib/x86_64-linux-gnu"));
        dirs.push(PathBuf::from("/usr/lib/aarch64-linux-gnu"));
    }
    dirs
}

/// Search `dirs` for the first existing NDI runtime dylib and return its path.
///
/// This is pure path arithmetic + a `Path::exists` probe — it does **not**
/// `dlopen` anything, so it is fully testable without the SDK. Returns
/// [`NdiSysError::RuntimeNotFound`] (carrying every probed path) if nothing
/// matches.
///
/// # Errors
/// [`NdiSysError::RuntimeNotFound`] when no candidate file exists.
pub fn find_runtime(dirs: &[PathBuf]) -> Result<PathBuf, NdiSysError> {
    let mut searched = Vec::new();
    for dir in dirs {
        for name in runtime_dylib_names() {
            let candidate = dir.join(name);
            if candidate.exists() {
                return Ok(candidate);
            }
            searched.push(candidate);
        }
    }
    Err(NdiSysError::RuntimeNotFound { searched })
}

/// An **opaque, non-null** pointer to the SDK function table returned by
/// `NDIlib_v6_load()`.
///
/// Multiview deliberately does **not** reproduce the proprietary `NDIlib_v5`
/// struct layout here (that would be a form of vendoring the SDK). The table is
/// carried as a `NonNull<c_void>`; consuming the individual function pointers is
/// a live-only concern handled where the real ABI is available. The pointer is
/// valid only while its owning [`NdiRuntime`] (and therefore the loaded
/// [`Library`]) is alive.
#[derive(Debug, Clone, Copy)]
pub struct NdiApiTable(NonNull<std::ffi::c_void>);

impl NdiApiTable {
    /// The raw table pointer, for the live FFI layer that knows the SDK ABI.
    #[must_use]
    pub fn as_ptr(self) -> *const std::ffi::c_void {
        self.0.as_ptr().cast_const()
    }

    /// Reinterpret the table as the typed [`NDIlib_v6`](ffi::NDIlib_v6) function
    /// table (NDI-L1; under the `bindings` feature).
    ///
    /// The returned pointer is valid **only while the owning [`NdiRuntime`] is
    /// alive** — it points into the loaded `Library`. The cast itself is sound (a
    /// pointer reinterpretation); dereferencing it to call a function pointer is
    /// the caller's `unsafe` step, performed in the consuming FFI layer.
    #[cfg(feature = "bindings")]
    #[must_use]
    pub fn v6(self) -> *const ffi::NDIlib_v6 {
        self.as_ptr().cast()
    }
}

/// A loaded NDI runtime: the owned [`Library`] plus the resolved function table.
///
/// Dropping it unloads the runtime (`Library`'s `Drop`), which invalidates the
/// table pointer — hence the table is only ever handed out borrowed from a live
/// `NdiRuntime`.
pub struct NdiRuntime {
    // Field order matters for drop: the table pointer is owned by `_lib`, so the
    // library must outlive any use of the table. `NdiRuntime` keeps them
    // together and never lets the table escape its lifetime.
    table: NdiApiTable,
    // Kept alive for the lifetime of the runtime; unloading it invalidates the
    // table. Never dropped before `table` is done being used (we never hand the
    // table out by value past `&self`).
    _lib: Library,
}

// The NDI loader entry point: `extern "C" fn() -> *const NDIlib_v5`. We treat
// the returned table as opaque (see `NdiApiTable`).
type NdiLoadFn = unsafe extern "C" fn() -> *const std::ffi::c_void;

impl NdiRuntime {
    /// Locate, open, and resolve the NDI runtime via the default search paths.
    ///
    /// Returns a typed [`NdiSysError`] — never a panic, never a block — when the
    /// runtime is absent, fails to open, or lacks the `NDIlib_v6_load` entry.
    ///
    /// # Errors
    /// See [`NdiSysError`]: not found / open failed / symbol missing / null table.
    pub fn load() -> Result<Self, NdiSysError> {
        let path = find_runtime(&default_search_paths())?;
        Self::load_from(&path)
    }

    /// Open and resolve a specific runtime dylib path (used by tests and when the
    /// operator pins an explicit path).
    ///
    /// # Errors
    /// See [`NdiSysError`].
    pub fn load_from(path: &Path) -> Result<Self, NdiSysError> {
        Self::load_named(path)
    }

    // reason: this is the crate's sole `unsafe` boundary — the raw `dlopen`
    // (`Library::new`) + `dlsym` (`get`) + the one call into the resolved
    // `NDIlib_v6_load`. It is exactly the FFI this leaf crate exists to isolate so
    // `multiview-output` stays `forbid(unsafe_code)`. Each `unsafe` use carries a
    // `// SAFETY:` note below.
    #[allow(unsafe_code)]
    fn load_named(path: &(impl AsRef<OsStr> + ?Sized)) -> Result<Self, NdiSysError> {
        let path_buf = PathBuf::from(path.as_ref());
        // SAFETY: We open an operator-provided dynamic library by path. Loading a
        // dylib runs its initialisers, which is inherently `unsafe`; we constrain
        // the input to a real filesystem path the caller chose (the NDI runtime),
        // surface any failure as a typed error, and never dereference anything
        // from it here — only resolve the documented `NDIlib_v6_load` symbol
        // below. The `Library` is owned by the returned `NdiRuntime`, so it stays
        // mapped for as long as the resolved table is used.
        let lib = unsafe { Library::new(path.as_ref()) }.map_err(|e| NdiSysError::OpenFailed {
            path: path_buf.clone(),
            detail: e.to_string(),
        })?;

        // SAFETY: We resolve the documented C entry point `NDIlib_v6_load` and
        // bind it to its known signature `extern "C" fn() -> *const table`. The
        // symbol is looked up by name; on success `libloading` guarantees it is a
        // valid function pointer into `lib`, which we keep alive. A missing symbol
        // is returned as a typed error, not a panic.
        let table_ptr = unsafe {
            let loader =
                lib.get::<NdiLoadFn>(NDI_LOAD_SYMBOL)
                    .map_err(|e| NdiSysError::SymbolMissing {
                        path: path_buf.clone(),
                        detail: e.to_string(),
                    })?;
            // SAFETY: `loader` is the resolved `NDIlib_v6_load`. Per the SDK it
            // takes no arguments and returns a pointer to the (statically-owned,
            // process-lifetime) function table; it has no preconditions. We only
            // null-check the result below and never dereference the table here.
            loader()
        };

        let table = NonNull::new(table_ptr.cast_mut())
            .map(NdiApiTable)
            .ok_or(NdiSysError::NullApiTable)?;

        Ok(Self { table, _lib: lib })
    }

    /// The resolved function table (borrowed for the runtime's lifetime).
    #[must_use]
    pub fn api_table(&self) -> NdiApiTable {
        self.table
    }
}

impl std::fmt::Debug for NdiRuntime {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NdiRuntime")
            .field("table", &self.table)
            .finish_non_exhaustive()
    }
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing
    )]
    use super::*;

    #[test]
    fn load_symbol_is_v6_and_nul_terminated() {
        // NDI 6 entry point — must be the v6 symbol, NUL-terminated for dlsym.
        assert_eq!(NDI_LOAD_SYMBOL, b"NDIlib_v6_load\0");
        assert_eq!(*NDI_LOAD_SYMBOL.last().unwrap(), 0);
    }

    #[test]
    fn search_paths_are_nonempty_and_names_versioned() {
        let dirs = default_search_paths();
        assert!(!dirs.is_empty(), "must probe at least one conventional dir");
        let names = runtime_dylib_names();
        assert!(!names.is_empty());
        // The runtime is never the unversioned-only name on Linux; a versioned
        // SONAME must be probed so a real install is found.
        #[cfg(not(target_os = "macos"))]
        assert!(names.iter().any(|n| n.contains(".so.")));
    }

    #[test]
    fn env_dir_is_searched_first() {
        let dir = tempfile::tempdir().unwrap();
        // SAFETY note: single-threaded test; we set + read one env var.
        std::env::set_var(NDI_RUNTIME_ENV, dir.path());
        let dirs = default_search_paths();
        std::env::remove_var(NDI_RUNTIME_ENV);
        assert_eq!(dirs.first().map(PathBuf::as_path), Some(dir.path()));
    }

    #[test]
    fn find_runtime_absent_reports_searched_paths_no_panic() {
        let dirs = vec![PathBuf::from("/nonexistent-ndi-dir-xyz")];
        match find_runtime(&dirs) {
            Err(NdiSysError::RuntimeNotFound { searched }) => {
                assert!(!searched.is_empty());
                assert!(searched
                    .iter()
                    .all(|p| p.starts_with("/nonexistent-ndi-dir-xyz")));
            }
            other => panic!("expected RuntimeNotFound, got {other:?}"),
        }
    }

    #[test]
    fn find_runtime_locates_a_present_candidate() {
        let dir = tempfile::tempdir().unwrap();
        let name = runtime_dylib_names()[0];
        let path = dir.path().join(name);
        std::fs::write(&path, b"not a real dylib").unwrap();
        let found = find_runtime(&[dir.path().to_path_buf()]).unwrap();
        assert_eq!(found, path);
    }

    #[test]
    fn load_from_missing_path_is_open_failed_not_panic() {
        // A path that exists-check would skip, but load_from opens directly: a
        // bogus path must surface OpenFailed, never panic or block.
        let err = NdiRuntime::load_from(Path::new("/nonexistent-ndi-dir-xyz/libndi.so.6"))
            .expect_err("must fail to open a missing dylib");
        assert!(matches!(err, NdiSysError::OpenFailed { .. }));
    }

    #[test]
    fn load_from_non_dylib_file_is_open_failed() {
        // A real file that is not a valid dylib must be OpenFailed, never a crash.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(runtime_dylib_names()[0]);
        std::fs::write(&path, b"definitely not an ELF/Mach-O dylib").unwrap();
        let err = NdiRuntime::load_from(&path).expect_err("garbage file must not open");
        assert!(matches!(err, NdiSysError::OpenFailed { .. }), "got {err:?}");
    }

    #[test]
    fn errors_display_without_panicking() {
        // Every variant must render a message (used in operator-facing status).
        let variants = [
            NdiSysError::RuntimeNotFound {
                searched: vec![PathBuf::from("/x")],
            },
            NdiSysError::OpenFailed {
                path: PathBuf::from("/x"),
                detail: "boom".into(),
            },
            NdiSysError::SymbolMissing {
                path: PathBuf::from("/x"),
                detail: "boom".into(),
            },
            NdiSysError::NullApiTable,
        ];
        for v in &variants {
            assert!(!v.to_string().is_empty());
        }
    }
}
