//! `OpenAPI` 3.1 document + Scalar try-it-out, and the `AsyncAPI` 3.0 document
//! (feature `openapi`, default on).
//!
//! Per ADR-W002 the REST spec is code-first via utoipa (verified `OpenAPI` 3.1
//! only). [`ApiDoc`] aggregates the path + schema definitions; [`openapi_router`]
//! serves the document at `/api/v1/openapi.json` and the Scalar UI at `/docs`.
//!
//! The realtime spec (`AsyncAPI` 3.0) is generated by `cargo xtask gen-asyncapi`
//! and committed to `docs/api/asyncapi.json`. It is embedded at compile time with
//! `include_str!` and served at `/asyncapi.json` — alongside the REST spec, not
//! under `/api/v1` (the realtime surface is transport-level, not REST-resource).
use axum::extract::State;
use axum::http::header;
use axum::response::IntoResponse;
use axum::Json;
use axum::Router;
use utoipa::OpenApi;
use utoipa_scalar::{Scalar, Servable};

use crate::state::AppState;

/// The `AsyncAPI` 3.0 document, embedded at compile time from the generated
/// file produced by `cargo xtask gen-asyncapi`. Served as-is; the `xtask` is
/// the authoritative generator and the JSON is committed to version control so
/// the binary is self-contained without a runtime filesystem dependency.
///
/// Path is relative to `crates/multiview-control/` (the crate root).
const ASYNCAPI_JSON: &str = include_str!("../../../docs/api/asyncapi.json");

/// The aggregate `OpenAPI` 3.1 document for the control API.
///
/// Paths and component schemas are registered here so the served
/// `openapi.json` is the single source of truth the SPA client is generated
/// from.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Multiview Control API",
        version = "1.0.0",
        description = "REST + WebSocket + SSE management API for the Multiview engine.",
        license(
            name = "Multiview Source-Available Non-Commercial License",
            url = "https://github.com/aperim/multiview/blob/main/LICENSE",
        ),
    ),
    paths(
        crate::routes::list_layouts,
        crate::routes::get_layout,
        crate::routes::create_layout,
        crate::routes::update_layout,
        crate::routes::delete_layout,
        crate::routes::sources::list_sources,
        crate::routes::sources::get_source,
        crate::routes::sources::create_source,
        crate::routes::sources::update_source,
        crate::routes::sources::delete_source,
        crate::routes::inputs::get_input_streams,
        crate::routes::outputs::list_outputs,
        crate::routes::outputs::get_output,
        crate::routes::outputs::create_output,
        crate::routes::outputs::update_output,
        crate::routes::outputs::delete_output,
        crate::routes::overlays::list_overlays,
        crate::routes::overlays::get_overlay,
        crate::routes::overlays::create_overlay,
        crate::routes::overlays::update_overlay,
        crate::routes::overlays::delete_overlay,
        crate::routes::probes::list_probes,
        crate::routes::probes::get_probe,
        crate::routes::probes::create_probe,
        crate::routes::probes::update_probe,
        crate::routes::probes::delete_probe,
        crate::routes::devices::list_devices,
        crate::routes::devices::get_device,
        crate::routes::devices::create_device,
        crate::routes::devices::update_device,
        crate::routes::devices::delete_device,
        crate::routes::devices::get_device_status,
        crate::routes::devices::probe_device,
        crate::routes::devices::set_mode,
        crate::routes::devices::reboot_device,
        crate::routes::devices::identify_device,
        crate::routes::devices::test_pattern,
        crate::routes::devices::source_candidates,
        crate::routes::devices::output_targets,
        crate::routes::discovery::scan_devices,
        crate::routes::discovery::list_discovered,
        crate::routes::sync_groups::list_sync_groups,
        crate::routes::sync_groups::get_sync_group,
        crate::routes::sync_groups::create_sync_group,
        crate::routes::sync_groups::update_sync_group,
        crate::routes::sync_groups::delete_sync_group,
        crate::routes::sync_groups::measure_sync_group,
        crate::routes::audio::get_audio_routing,
        crate::routes::audio::put_audio_routing,
        crate::routes::cmd_apply_layout,
        crate::routes::alarms::list_alarms,
        crate::routes::alarms::ack_alarm,
        crate::routes::health::list_health,
        crate::routes::licence::get_licence,
        crate::routes::licence::install_lease,
        crate::routes::licence::get_challenge,
        crate::routes::licence::get_heartbeat_status,
        crate::routes::mesh::get_status,
        crate::routes::mesh::set_relay,
        crate::routes::mesh::list_peers,
        crate::routes::telemetry::get_consent,
        crate::routes::telemetry::set_consent,
        crate::routes::telemetry::get_schema,
        crate::routes::telemetry::request_snapshot,
        crate::routes::telemetry::get_snapshot,
        crate::routes::salvos::list_salvos,
        crate::routes::salvos::put_salvo,
        crate::routes::salvos::arm_salvo,
        crate::routes::salvos::take_salvo,
        crate::routes::salvos::cancel_salvo,
        crate::routes::account::fire_salvo,
        crate::routes::account::list_account_audit,
        crate::routes::account::list_pending_actions,
        crate::routes::account::cancel_action,
        crate::routes::routing::plan_route,
        crate::routes::routing::take_route,
        crate::routes::tally::list_tally,
        crate::routes::tally::list_profiles,
        crate::routes::tally::put_profile,
        crate::routes::tally::set_override,
        crate::routes::tally::clear_override,
        crate::routes::audit::list_audit,
        crate::routes::config::export_config,
        crate::routes::preview::program_whep_open,
        crate::routes::preview::program_whep_close,
        crate::routes::preview::input_whep_open,
        crate::routes::preview::input_whep_close,
        crate::routes::preview::output_whep_open,
        crate::routes::preview::output_whep_close,
        crate::nmos::get_self,
        crate::nmos::list_devices,
        crate::nmos::list_senders,
        crate::nmos::list_receivers,
        crate::nmos::patch_staged,
    ),
    components(schemas(
        crate::problem::Problem,
        crate::repository::Layout,
        crate::repository::LayoutInput,
        crate::resource_store::Resource,
        crate::resource_store::ResourceInput,
        crate::routes::AcceptedBody,
        crate::routes::SwapRequest,
        crate::routes::ApplyLayoutRequest,
        crate::auth::Role,
        crate::command::OperationId,
        crate::audit::AuditEntry,
        crate::audit::AuditAction,
        // Account-side append-only audit + remote-actions (Conspect, ADR-0053).
        crate::account_audit::AccountAuditEntry,
        crate::account_audit::AccountAuditKind,
        crate::account_audit::AccountAuditPage,
        crate::pending_actions::PendingAction,
        crate::pending_actions::PendingActionKind,
        crate::pending_actions::PendingActionState,
        crate::routes::account::CancelledBody,
        crate::routes::account::FiredBody,
        crate::versioning::ConfigRevision,
        crate::versioning::RevisionId,
        crate::versioning::DocumentDiff,
        crate::routes::config::CommitRequest,
        crate::routes::config::RollbackRequest,
        crate::openapi_schemas::AlarmRecordDoc,
        crate::openapi_schemas::SourceBodyDoc,
        crate::openapi_schemas::SourceKindDoc,
        crate::openapi_schemas::SourceAuthDoc,
        crate::openapi_schemas::ColorOverrideDoc,
        crate::openapi_schemas::CaptionSelectorDoc,
        crate::openapi_schemas::DevicePinDoc,
        crate::openapi_schemas::PinVendorDoc,
        crate::openapi_schemas::RtspOptionsDoc,
        crate::openapi_schemas::ClockFaceDoc,
        crate::openapi_schemas::TimerTargetDoc,
        crate::openapi_schemas::TimerDirectionDoc,
        crate::openapi_schemas::TimerOnTargetDoc,
        crate::openapi_schemas::TimerFormatDoc,
        crate::openapi_schemas::SourceWallClockDoc,
        crate::openapi_schemas::WallClockUseDoc,
        crate::openapi_schemas::OutputAudioModeDoc,
        crate::openapi_schemas::OutputBodyDoc,
        crate::openapi_schemas::OutputAudioDoc,
        crate::openapi_schemas::AudioChannelsDoc,
        crate::openapi_schemas::AudioRouteDoc,
        crate::openapi_schemas::AudioRoutingDoc,
        crate::openapi_schemas::AudioRoutingStateDoc,
        crate::openapi_schemas::OverlayBodyDoc,
        crate::openapi_schemas::ProbeBodyDoc,
        crate::openapi_schemas::ProbeKindDoc,
        crate::openapi_schemas::DetectionZoneDoc,
        crate::openapi_schemas::DwellDoc,
        crate::openapi_schemas::LoudnessTargetDoc,
        crate::openapi_schemas::SourceResourceInputDoc,
        crate::openapi_schemas::OutputResourceInputDoc,
        crate::openapi_schemas::OverlayResourceInputDoc,
        crate::openapi_schemas::ProbeResourceInputDoc,
        crate::openapi_schemas::DeviceDriverDoc,
        crate::openapi_schemas::DeviceAuthDoc,
        crate::openapi_schemas::ReconnectPolicyDoc,
        crate::openapi_schemas::DeviceBodyDoc,
        crate::openapi_schemas::DeviceResourceInputDoc,
        crate::openapi_schemas::SyncMemberDoc,
        crate::openapi_schemas::SyncGroupBodyDoc,
        crate::openapi_schemas::SyncGroupResourceInputDoc,
        crate::openapi_schemas::DeviceStatusDoc,
        crate::routes::devices::SetModeRequest,
        crate::routes::devices::SetModeAccepted,
        crate::devices::projection::SourceCandidate,
        crate::devices::projection::OutputTarget,
        crate::devices::discovery::DiscoveredService,
        crate::devices::discovery::DiscoveredEndpoint,
        crate::devices::discovery::DiscoveryDriverKind,
        crate::devices::discovery::TxtRecord,
        crate::routes::discovery::ScanAccepted,
        crate::openapi_schemas::HealthWarningDoc,
        crate::openapi_schemas::WarningSeverityDoc,
        crate::openapi_schemas::WarningCodeDoc,
        // Local licence (Conspect, CONSPECT-1 / ADR-0050): the computed licence
        // resource + the lease-install response. The Doc mirrors match the
        // multiview-licence serde shapes (pinned by a round-trip test).
        crate::routes::licence::LicenceResource,
        crate::routes::licence::LeaseInstalled,
        crate::routes::licence::HeartbeatStatus,
        crate::openapi_schemas::LicenceStatusDoc,
        crate::openapi_schemas::LeaseSourceDoc,
        crate::openapi_schemas::HardwareClassDoc,
        crate::openapi_schemas::HardwareClassViewDoc,
        crate::openapi_schemas::GpuLimitDoc,
        crate::openapi_schemas::LadderStateDoc,
        crate::openapi_schemas::EnforcementLevelDoc,
        crate::openapi_schemas::LeaseDoc,
        crate::openapi_schemas::LeaseInstalledDoc,
        // Local mesh (Conspect, CONSPECT-3a / ADR-0051): the always-on
        // discovery + relay status, the relay opt-in request body, and the
        // untrusted discovered-peer inventory. The Doc mirrors match the
        // multiview-mesh serde shapes (pinned byte-for-byte by tests/mesh.rs).
        crate::routes::mesh::RelaySetRequest,
        // Telemetry pipe (Conspect, ADR-0052): the opt-in daily-pipe consent
        // document + request body, the published schema (sent + never-sent), and
        // the diagnostics-snapshot bundle (logs + engine state, never media). The
        // telemetry consent is separate from the licensing heartbeat (two-pipe).
        crate::routes::telemetry::ConsentResource,
        crate::routes::telemetry::ConsentSetRequest,
        crate::routes::telemetry::TelemetrySchema,
        crate::routes::telemetry::SnapshotAccepted,
        crate::routes::telemetry::DiagnosticsSnapshot,
        crate::routes::telemetry::DiagnosticsBody,
        crate::routes::telemetry::UtilisationReport,
        crate::routes::telemetry::ReconnectReport,
        crate::routes::telemetry::ShedReport,
        crate::routes::telemetry::IncidentReport,
        crate::telemetry_consent::ConsentActor,
        crate::telemetry_consent::SnapshotStatus,
        crate::openapi_schemas::DiscoveryModeDoc,
        crate::openapi_schemas::MeshRoleDoc,
        crate::openapi_schemas::MeshStatusDoc,
        crate::openapi_schemas::MeshPeerDoc,
        crate::openapi_schemas::AlarmKindDoc,
        crate::openapi_schemas::AlarmScopeDoc,
        crate::openapi_schemas::AckStateDoc,
        crate::openapi_schemas::PerceivedSeverityDoc,
        crate::openapi_schemas::TallyColorDoc,
        crate::openapi_schemas::BusSourceDoc,
        crate::openapi_schemas::TallyStateDoc,
        crate::openapi_schemas::TallyTargetDoc,
        crate::openapi_schemas::TallyEntryDoc,
        crate::openapi_schemas::OverrideRequestDoc,
        crate::openapi_schemas::ClearOverrideRequestDoc,
        crate::openapi_schemas::SourceRecallDoc,
        crate::openapi_schemas::TallyRecallDoc,
        crate::openapi_schemas::UmdRecallDoc,
        crate::openapi_schemas::SalvoDoc,
        crate::openapi_schemas::BitColorDoc,
        crate::openapi_schemas::IndexCellDoc,
        crate::openapi_schemas::TallyProfileDoc,
        crate::openapi_schemas::StreamInventoryDoc,
        crate::openapi_schemas::StreamDescriptorDoc,
        crate::openapi_schemas::StableStreamIdDoc,
        crate::openapi_schemas::StabilityTierDoc,
        crate::openapi_schemas::StreamKindDoc,
        crate::openapi_schemas::StreamDetailDoc,
        crate::openapi_schemas::DataKindDoc,
        crate::openapi_schemas::TcSourceKindDoc,
        // Per-stream crosspoint routing (RT-11): plan/take request + response.
        crate::openapi_schemas::StreamSelectorDoc,
        crate::openapi_schemas::StreamRefDoc,
        crate::openapi_schemas::RouteTargetDoc,
        crate::routes::routing::RouteTakeRequest,
        crate::routes::routing::TakeApplied,
        crate::routing::RoutePlan,
        crate::routing::RouteClass,
        crate::nmos::is04::Node,
        crate::nmos::is04::Device,
        crate::nmos::is04::Sender,
        crate::nmos::is04::Receiver,
        crate::nmos::is04::ResourceCore,
        crate::nmos::is04::MediaFormat,
        crate::nmos::is04::Registration,
        crate::nmos::is04::ResourceType,
        crate::nmos::is05::ConnectionRequest,
        crate::nmos::is05::ConnectionState,
        crate::nmos::is05::Activation,
        crate::nmos::is05::ActivationMode,
        crate::nmos::is05::TransportParams,
        crate::nmos::is08::ChannelMap,
        crate::nmos::is08::ChannelSource,
        crate::nmos::is10::Is10Claims,
        crate::nmos::is10::NmosApiClaim,
        crate::nmos::is10::NmosAccess,
    )),
    tags(
        (name = "layouts", description = "Layout resource CRUD"),
        (name = "sources", description = "Source (managed input) resource CRUD"),
        (name = "inputs", description = "Input elementary-stream inventory (read-only discovery)"),
        (name = "outputs", description = "Output (managed sink/server) resource CRUD"),
        (name = "overlays", description = "Overlay (managed overlay layer) resource CRUD"),
        (name = "probes", description = "Probe (per-cell fail-state detection: black/freeze/silence/loudness) resource CRUD"),
        (name = "devices", description = "Managed-device registry CRUD + status + bare-verb actions + stream-binding projections (ADR-M008/M009/W017)"),
        (name = "discovery", description = "mDNS device discovery: scan + the untrusted inventory requiring explicit confirm-adopt (ADR-M008 §6 / ADR-0041)"),
        (name = "sync-groups", description = "Presentation-sync-group CRUD + skew measurement (ADR-M008/M010)"),
        (name = "audio", description = "Audio routing: the document-level program-bus membership + discrete-track wiring per-output selections resolve against"),
        (name = "commands", description = "Operational commands (start/stop/swap)"),
        (name = "alarms", description = "Monitoring alarms: list + acknowledge"),
        (name = "health", description = "Health warnings: active capability mismatches + remediation (read-only)"),
        (name = "licence", description = "Local licence (Conspect): the computed licence resource + ladder (enforcement is data), lease install, and the salted challenge export. All-local; never off air."),
        (name = "mesh", description = "Local mesh (Conspect): always-on mDNS discovery status (no off switch), the relay opt-in toggle, and the untrusted discovered-peer inventory. Control-plane only; never back-pressures the engine."),
        (name = "telemetry", description = "Telemetry pipe (Conspect): the opt-in daily-pipe consent (off by default, last-writer-wins), the published schema (sent + never-sent), and the §4.2 diagnostics snapshot (logs + engine state, never media). DISTINCT from the licensing heartbeat (under /licensing) — the two pipes are never co-mingled. Consent gates no local route; control-plane only."),
        (name = "salvos", description = "Salvo definitions + arm/take/cancel"),
        (name = "routing", description = "Per-stream crosspoint routing: classify (plan) + apply (take)"),
        (name = "tally", description = "Tally state, profiles, and manual override"),
        (name = "audit", description = "Read-only change audit log (who/what/when)"),
        (name = "account", description = "Account-side (Conspect): append-only audit (cursor-paginated), pending remote-actions strip + local-wins cancel, and named-salvo fire. Locally drivable now; portal-fed over the heartbeat/relay transport later."),
        (name = "preview", description = "Live preview: WHEP focus sessions per scope (program/input/output)"),
        (name = "config", description = "Config/layout versioning: revisions, diff, rollback"),
        (name = "nmos", description = "AMWA NMOS Node API: IS-04 resources + IS-05 connection"),
        (name = "realtime", description = "WebSocket + SSE event stream"),
    )
)]
pub struct ApiDoc;

impl ApiDoc {
    /// The static list of REST routes this API exposes, in the order they are
    /// registered. Used by tests to assert the surface is complete without
    /// depending on utoipa's `#[utoipa::path]` macro wiring for every handler.
    // This is a single flat `(method, path)` table mirroring the router; it grows
    // by one line per route as the surface expands (now past 100 with the
    // Conspect licence routes). Splitting it would only obscure the one-line-per-
    // route correspondence the test relies on, so the line-count lint is allowed
    // here with justification.
    #[allow(clippy::too_many_lines)]
    #[must_use]
    pub fn rest_routes() -> &'static [(&'static str, &'static str)] {
        REST_ROUTES
    }
}

/// The static REST-route surface, kept as a module-level `const` so
/// [`ApiDoc::rest_routes`] stays a one-liner (the table is data, not logic).
const REST_ROUTES: &[(&str, &str)] = &[
    ("GET", "/api/v1/layouts"),
    ("GET", "/api/v1/layouts/{id}"),
    ("POST", "/api/v1/layouts/{id}"),
    ("PUT", "/api/v1/layouts/{id}"),
    ("DELETE", "/api/v1/layouts/{id}"),
    ("GET", "/api/v1/sources"),
    ("GET", "/api/v1/sources/{id}"),
    ("POST", "/api/v1/sources/{id}"),
    ("PUT", "/api/v1/sources/{id}"),
    ("DELETE", "/api/v1/sources/{id}"),
    // Read-only input elementary-stream inventory (RT-3).
    ("GET", "/api/v1/inputs/{id}/streams"),
    ("GET", "/api/v1/outputs"),
    ("GET", "/api/v1/outputs/{id}"),
    ("POST", "/api/v1/outputs/{id}"),
    ("PUT", "/api/v1/outputs/{id}"),
    ("DELETE", "/api/v1/outputs/{id}"),
    // The audio-routing singleton document (GET is 404-free).
    ("GET", "/api/v1/audio-routing"),
    ("PUT", "/api/v1/audio-routing"),
    ("GET", "/api/v1/overlays"),
    ("GET", "/api/v1/overlays/{id}"),
    ("POST", "/api/v1/overlays/{id}"),
    ("PUT", "/api/v1/overlays/{id}"),
    ("DELETE", "/api/v1/overlays/{id}"),
    ("GET", "/api/v1/probes"),
    ("GET", "/api/v1/probes/{id}"),
    ("POST", "/api/v1/probes/{id}"),
    ("PUT", "/api/v1/probes/{id}"),
    ("DELETE", "/api/v1/probes/{id}"),
    // Managed-devices registry CRUD + status + actions + projections.
    ("GET", "/api/v1/devices"),
    ("GET", "/api/v1/devices/{id}"),
    ("POST", "/api/v1/devices/{id}"),
    ("PUT", "/api/v1/devices/{id}"),
    ("DELETE", "/api/v1/devices/{id}"),
    ("GET", "/api/v1/devices/{id}/status"),
    ("POST", "/api/v1/devices/{id}/probe"),
    ("POST", "/api/v1/devices/{id}/set-mode"),
    ("POST", "/api/v1/devices/{id}/reboot"),
    ("POST", "/api/v1/devices/{id}/identify"),
    ("POST", "/api/v1/devices/{id}/test-pattern"),
    ("GET", "/api/v1/devices/{id}/source-candidates"),
    ("GET", "/api/v1/devices/{id}/output-targets"),
    // mDNS device discovery (ADR-M008 §6 / ADR-0041 untrusted inventory).
    ("POST", "/api/v1/discovery/devices/scan"),
    ("GET", "/api/v1/discovery/devices"),
    // Presentation-sync-groups CRUD + measure.
    ("GET", "/api/v1/sync-groups"),
    ("GET", "/api/v1/sync-groups/{id}"),
    ("POST", "/api/v1/sync-groups/{id}"),
    ("PUT", "/api/v1/sync-groups/{id}"),
    ("DELETE", "/api/v1/sync-groups/{id}"),
    ("POST", "/api/v1/sync-groups/{id}/measure"),
    ("POST", "/api/v1/commands/start"),
    ("POST", "/api/v1/commands/stop"),
    ("POST", "/api/v1/commands/swap"),
    ("POST", "/api/v1/commands/apply-layout"),
    ("GET", "/api/v1/alarms"),
    ("POST", "/api/v1/alarms/{id}/ack"),
    // Read-only health warnings (SA-0 / ADR-0035).
    ("GET", "/api/v1/health"),
    ("GET", "/api/v1/licence"),
    ("POST", "/api/v1/licence/lease"),
    ("GET", "/api/v1/licence/challenge"),
    ("GET", "/api/v1/licensing/heartbeat-status"),
    // Local mesh (Conspect, CONSPECT-3a / ADR-0051): always-on discovery
    // status (GET-only — no off switch, the spec's locked row), the relay
    // opt-in toggle, and the untrusted discovered-peer inventory.
    ("GET", "/api/v1/mesh/status"),
    ("PUT", "/api/v1/mesh/relay"),
    ("GET", "/api/v1/mesh/peers"),
    // Telemetry pipe (Conspect, ADR-0052): opt-in daily-pipe consent (off by
    // default, LWW) + the published schema (sent + never-sent). Under
    // `/telemetry/`, NEVER `/licensing/` (the two-pipe separation). Consent gates
    // no local route.
    ("GET", "/api/v1/telemetry/consent"),
    ("PUT", "/api/v1/telemetry/consent"),
    ("GET", "/api/v1/telemetry/schema"),
    // Diagnostics snapshot (Conspect, spec §4.2 / ADR-0053): the one-button
    // support bundle (logs + engine state, never media) — POST → 202, GET by id.
    ("POST", "/api/v1/diagnostics/snapshot"),
    ("GET", "/api/v1/diagnostics/{id}"),
    ("GET", "/api/v1/salvos"),
    ("GET", "/api/v1/salvos/{id}"),
    ("PUT", "/api/v1/salvos/{id}"),
    ("DELETE", "/api/v1/salvos/{id}"),
    ("POST", "/api/v1/salvos/{id}/arm"),
    ("POST", "/api/v1/salvos/{id}/take"),
    ("POST", "/api/v1/salvos/{id}/cancel"),
    // Salvo parity (Conspect §11): fire a named salvo → 202.
    ("POST", "/api/v1/salvos/{id}/fire"),
    // Per-stream crosspoint routing (RT-11): plan (classify) + take (apply).
    ("POST", "/api/v1/routing/plan"),
    ("POST", "/api/v1/routing/{kind}/take"),
    ("GET", "/api/v1/tally"),
    ("PUT", "/api/v1/tally/override"),
    ("DELETE", "/api/v1/tally/override"),
    ("GET", "/api/v1/tally/profiles"),
    ("GET", "/api/v1/tally/profiles/{id}"),
    ("PUT", "/api/v1/tally/profiles/{id}"),
    ("DELETE", "/api/v1/tally/profiles/{id}"),
    // WHEP focus sessions (sub-second WebRTC preview) per scope.
    ("POST", "/api/v1/preview/program/whep"),
    ("DELETE", "/api/v1/preview/program/whep/{session_id}"),
    ("POST", "/api/v1/preview/inputs/{id}/whep"),
    ("DELETE", "/api/v1/preview/inputs/{id}/whep/{session_id}"),
    ("POST", "/api/v1/preview/outputs/{id}/whep"),
    ("DELETE", "/api/v1/preview/outputs/{id}/whep/{session_id}"),
    // Read-only change audit log.
    ("GET", "/api/v1/audit"),
    // Account-side append-only audit (Conspect §10/§11): cursor-paginated.
    ("GET", "/api/v1/account/audit"),
    // Pending remote-actions strip + local cancel (local always wins).
    ("GET", "/api/v1/actions/pending"),
    ("POST", "/api/v1/actions/{id}/cancel"),
    // Config versioning: history + commit, single revision, diff, rollback.
    ("GET", "/api/v1/config/{target}"),
    ("PUT", "/api/v1/config/{target}"),
    ("GET", "/api/v1/config/{target}/rev/{revision}"),
    ("GET", "/api/v1/config/{target}/diff"),
    ("POST", "/api/v1/config/{target}/rollback"),
    // AsyncAPI 3.0 document (realtime/WebSocket spec, generated by xtask).
    ("GET", "/asyncapi.json"),
    // AMWA NMOS Node API (under the standardised /x-nmos base).
    ("GET", "/x-nmos/node/v1.3/self"),
    ("GET", "/x-nmos/node/v1.3/devices"),
    ("GET", "/x-nmos/node/v1.3/senders"),
    ("GET", "/x-nmos/node/v1.3/receivers"),
    (
        "GET",
        "/x-nmos/connection/v1.1/single/receivers/{id}/active",
    ),
    (
        "PATCH",
        "/x-nmos/connection/v1.1/single/receivers/{id}/staged",
    ),
    ("GET", "/api/v1/ws"),
    ("GET", "/api/v1/events"),
];

/// Serve the raw `OpenAPI` document as JSON.
async fn openapi_json(State(_state): State<AppState>) -> Json<utoipa::openapi::OpenApi> {
    Json(ApiDoc::openapi())
}

/// Serve the embedded `AsyncAPI` 3.0 document as JSON.
///
/// The document is the committed output of `cargo xtask gen-asyncapi`
/// (`docs/api/asyncapi.json`), embedded at compile time. No `AppState` is
/// needed — the spec is static and carries no session-specific data.
async fn asyncapi_json() -> impl IntoResponse {
    (
        [
            (
                header::CONTENT_TYPE,
                // Serve as `application/json` rather than a vendor MIME type so
                // browsers and plain HTTP clients can consume it without special
                // Accept headers (mirrors the openapi.json convention above).
                "application/json",
            ),
            (
                header::CACHE_CONTROL,
                // The document changes only on re-deploy; `no-cache` means the
                // browser re-validates on every navigation but can serve a
                // cached copy when the ETag matches, so latency stays low.
                "no-cache",
            ),
        ],
        ASYNCAPI_JSON,
    )
}

/// Build the router serving the `OpenAPI` JSON (`/api/v1/openapi.json`), the
/// Scalar UI (`/docs`), and the `AsyncAPI` 3.0 JSON (`/asyncapi.json`).
pub fn openapi_router() -> Router<AppState> {
    Router::new()
        .route("/api/v1/openapi.json", axum::routing::get(openapi_json))
        .route("/asyncapi.json", axum::routing::get(asyncapi_json))
        .merge(Scalar::with_url("/docs", ApiDoc::openapi()))
}
