//! `OpenAPI` 3.1 document + Scalar try-it-out, and the `AsyncAPI` 3.0 document
//! (feature `openapi`, default on).
//!
//! Per ADR-W002 the REST spec is code-first via utoipa (verified `OpenAPI` 3.1
//! only). [`ApiDoc`] aggregates the path + schema definitions; [`openapi_router`]
//! serves the document at `/api/v1/openapi.json` and the Scalar UI at `/docs`.
//!
//! The realtime spec (`AsyncAPI` 3.0) is generated by `cargo xtask gen-asyncapi`
//! and committed to `docs/api/asyncapi.json`. It is embedded at compile time with
//! `include_str!` and served at `/asyncapi.json` — alongside the REST spec, not
//! under `/api/v1` (the realtime surface is transport-level, not REST-resource).
use axum::extract::State;
use axum::http::header;
use axum::response::IntoResponse;
use axum::Json;
use axum::Router;
use utoipa::OpenApi;
use utoipa_scalar::{Scalar, Servable};

use crate::state::AppState;

/// The `AsyncAPI` 3.0 document, embedded at compile time from the generated
/// file produced by `cargo xtask gen-asyncapi`. Served as-is; the `xtask` is
/// the authoritative generator and the JSON is committed to version control so
/// the binary is self-contained without a runtime filesystem dependency.
///
/// Path is relative to `crates/multiview-control/` (the crate root).
const ASYNCAPI_JSON: &str = include_str!("../../../docs/api/asyncapi.json");

/// The aggregate `OpenAPI` 3.1 document for the control API.
///
/// Paths and component schemas are registered here so the served
/// `openapi.json` is the single source of truth the SPA client is generated
/// from.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Multiview Control API",
        version = "1.0.0",
        description = "REST + WebSocket + SSE management API for the Multiview engine.",
        license(
            name = "Multiview Source-Available Non-Commercial License",
            url = "https://github.com/aperim/multiview/blob/main/LICENSE",
        ),
    ),
    paths(
        crate::routes::list_layouts,
        crate::routes::get_layout,
        crate::routes::create_layout,
        crate::routes::update_layout,
        crate::routes::delete_layout,
        crate::routes::sources::list_sources,
        crate::routes::sources::get_source,
        crate::routes::sources::create_source,
        crate::routes::sources::update_source,
        crate::routes::sources::delete_source,
        crate::routes::inputs::get_input_streams,
        crate::routes::outputs::list_outputs,
        crate::routes::outputs::get_output,
        crate::routes::outputs::create_output,
        crate::routes::outputs::update_output,
        crate::routes::outputs::delete_output,
        crate::routes::overlays::list_overlays,
        crate::routes::overlays::get_overlay,
        crate::routes::overlays::create_overlay,
        crate::routes::overlays::update_overlay,
        crate::routes::overlays::delete_overlay,
        crate::routes::probes::list_probes,
        crate::routes::probes::get_probe,
        crate::routes::probes::create_probe,
        crate::routes::probes::update_probe,
        crate::routes::probes::delete_probe,
        crate::routes::cmd_apply_layout,
        crate::routes::alarms::list_alarms,
        crate::routes::alarms::ack_alarm,
        crate::routes::health::list_health,
        crate::routes::salvos::list_salvos,
        crate::routes::salvos::put_salvo,
        crate::routes::salvos::arm_salvo,
        crate::routes::salvos::take_salvo,
        crate::routes::salvos::cancel_salvo,
        crate::routes::routing::plan_route,
        crate::routes::routing::take_route,
        crate::routes::tally::list_tally,
        crate::routes::tally::list_profiles,
        crate::routes::tally::put_profile,
        crate::routes::tally::set_override,
        crate::routes::tally::clear_override,
        crate::routes::audit::list_audit,
        crate::routes::config::export_config,
        crate::routes::preview::program_whep_open,
        crate::routes::preview::program_whep_close,
        crate::routes::preview::input_whep_open,
        crate::routes::preview::input_whep_close,
        crate::routes::preview::output_whep_open,
        crate::routes::preview::output_whep_close,
        crate::nmos::get_self,
        crate::nmos::list_devices,
        crate::nmos::list_senders,
        crate::nmos::list_receivers,
        crate::nmos::patch_staged,
    ),
    components(schemas(
        crate::problem::Problem,
        crate::repository::Layout,
        crate::repository::LayoutInput,
        crate::resource_store::Resource,
        crate::resource_store::ResourceInput,
        crate::routes::AcceptedBody,
        crate::routes::SwapRequest,
        crate::routes::ApplyLayoutRequest,
        crate::auth::Role,
        crate::command::OperationId,
        crate::audit::AuditEntry,
        crate::audit::AuditAction,
        crate::versioning::ConfigRevision,
        crate::versioning::RevisionId,
        crate::versioning::DocumentDiff,
        crate::routes::config::CommitRequest,
        crate::routes::config::RollbackRequest,
        crate::openapi_schemas::AlarmRecordDoc,
        crate::openapi_schemas::SourceBodyDoc,
        crate::openapi_schemas::SourceKindDoc,
        crate::openapi_schemas::SourceAuthDoc,
        crate::openapi_schemas::ColorOverrideDoc,
        crate::openapi_schemas::CaptionSelectorDoc,
        crate::openapi_schemas::DevicePinDoc,
        crate::openapi_schemas::PinVendorDoc,
        crate::openapi_schemas::RtspOptionsDoc,
        crate::openapi_schemas::ClockFaceDoc,
        crate::openapi_schemas::SourceWallClockDoc,
        crate::openapi_schemas::WallClockUseDoc,
        crate::openapi_schemas::OutputAudioModeDoc,
        crate::openapi_schemas::OutputBodyDoc,
        crate::openapi_schemas::OutputAudioDoc,
        crate::openapi_schemas::OverlayBodyDoc,
        crate::openapi_schemas::ProbeBodyDoc,
        crate::openapi_schemas::ProbeKindDoc,
        crate::openapi_schemas::DetectionZoneDoc,
        crate::openapi_schemas::DwellDoc,
        crate::openapi_schemas::LoudnessTargetDoc,
        crate::openapi_schemas::SourceResourceInputDoc,
        crate::openapi_schemas::OutputResourceInputDoc,
        crate::openapi_schemas::OverlayResourceInputDoc,
        crate::openapi_schemas::ProbeResourceInputDoc,
        crate::openapi_schemas::HealthWarningDoc,
        crate::openapi_schemas::WarningSeverityDoc,
        crate::openapi_schemas::WarningCodeDoc,
        crate::openapi_schemas::AlarmKindDoc,
        crate::openapi_schemas::AlarmScopeDoc,
        crate::openapi_schemas::AckStateDoc,
        crate::openapi_schemas::PerceivedSeverityDoc,
        crate::openapi_schemas::TallyColorDoc,
        crate::openapi_schemas::BusSourceDoc,
        crate::openapi_schemas::TallyStateDoc,
        crate::openapi_schemas::TallyTargetDoc,
        crate::openapi_schemas::TallyEntryDoc,
        crate::openapi_schemas::OverrideRequestDoc,
        crate::openapi_schemas::ClearOverrideRequestDoc,
        crate::openapi_schemas::SourceRecallDoc,
        crate::openapi_schemas::TallyRecallDoc,
        crate::openapi_schemas::UmdRecallDoc,
        crate::openapi_schemas::SalvoDoc,
        crate::openapi_schemas::BitColorDoc,
        crate::openapi_schemas::IndexCellDoc,
        crate::openapi_schemas::TallyProfileDoc,
        crate::openapi_schemas::StreamInventoryDoc,
        crate::openapi_schemas::StreamDescriptorDoc,
        crate::openapi_schemas::StableStreamIdDoc,
        crate::openapi_schemas::StabilityTierDoc,
        crate::openapi_schemas::StreamKindDoc,
        crate::openapi_schemas::StreamDetailDoc,
        crate::openapi_schemas::DataKindDoc,
        crate::openapi_schemas::TcSourceKindDoc,
        // Per-stream crosspoint routing (RT-11): plan/take request + response.
        crate::openapi_schemas::StreamSelectorDoc,
        crate::openapi_schemas::StreamRefDoc,
        crate::openapi_schemas::RouteTargetDoc,
        crate::routes::routing::RouteTakeRequest,
        crate::routes::routing::TakeApplied,
        crate::routing::RoutePlan,
        crate::routing::RouteClass,
        crate::nmos::is04::Node,
        crate::nmos::is04::Device,
        crate::nmos::is04::Sender,
        crate::nmos::is04::Receiver,
        crate::nmos::is04::ResourceCore,
        crate::nmos::is04::MediaFormat,
        crate::nmos::is04::Registration,
        crate::nmos::is04::ResourceType,
        crate::nmos::is05::ConnectionRequest,
        crate::nmos::is05::ConnectionState,
        crate::nmos::is05::Activation,
        crate::nmos::is05::ActivationMode,
        crate::nmos::is05::TransportParams,
        crate::nmos::is08::ChannelMap,
        crate::nmos::is08::ChannelSource,
        crate::nmos::is10::Is10Claims,
        crate::nmos::is10::NmosApiClaim,
        crate::nmos::is10::NmosAccess,
    )),
    tags(
        (name = "layouts", description = "Layout resource CRUD"),
        (name = "sources", description = "Source (managed input) resource CRUD"),
        (name = "inputs", description = "Input elementary-stream inventory (read-only discovery)"),
        (name = "outputs", description = "Output (managed sink/server) resource CRUD"),
        (name = "overlays", description = "Overlay (managed overlay layer) resource CRUD"),
        (name = "probes", description = "Probe (per-cell fail-state detection: black/freeze/silence/loudness) resource CRUD"),
        (name = "commands", description = "Operational commands (start/stop/swap)"),
        (name = "alarms", description = "Monitoring alarms: list + acknowledge"),
        (name = "health", description = "Health warnings: active capability mismatches + remediation (read-only)"),
        (name = "salvos", description = "Salvo definitions + arm/take/cancel"),
        (name = "routing", description = "Per-stream crosspoint routing: classify (plan) + apply (take)"),
        (name = "tally", description = "Tally state, profiles, and manual override"),
        (name = "audit", description = "Read-only change audit log (who/what/when)"),
        (name = "preview", description = "Live preview: WHEP focus sessions per scope (program/input/output)"),
        (name = "config", description = "Config/layout versioning: revisions, diff, rollback"),
        (name = "nmos", description = "AMWA NMOS Node API: IS-04 resources + IS-05 connection"),
        (name = "realtime", description = "WebSocket + SSE event stream"),
    )
)]
pub struct ApiDoc;

impl ApiDoc {
    /// The static list of REST routes this API exposes, in the order they are
    /// registered. Used by tests to assert the surface is complete without
    /// depending on utoipa's `#[utoipa::path]` macro wiring for every handler.
    #[must_use]
    pub fn rest_routes() -> &'static [(&'static str, &'static str)] {
        &[
            ("GET", "/api/v1/layouts"),
            ("GET", "/api/v1/layouts/{id}"),
            ("POST", "/api/v1/layouts/{id}"),
            ("PUT", "/api/v1/layouts/{id}"),
            ("DELETE", "/api/v1/layouts/{id}"),
            ("GET", "/api/v1/sources"),
            ("GET", "/api/v1/sources/{id}"),
            ("POST", "/api/v1/sources/{id}"),
            ("PUT", "/api/v1/sources/{id}"),
            ("DELETE", "/api/v1/sources/{id}"),
            // Read-only input elementary-stream inventory (RT-3).
            ("GET", "/api/v1/inputs/{id}/streams"),
            ("GET", "/api/v1/outputs"),
            ("GET", "/api/v1/outputs/{id}"),
            ("POST", "/api/v1/outputs/{id}"),
            ("PUT", "/api/v1/outputs/{id}"),
            ("DELETE", "/api/v1/outputs/{id}"),
            ("GET", "/api/v1/overlays"),
            ("GET", "/api/v1/overlays/{id}"),
            ("POST", "/api/v1/overlays/{id}"),
            ("PUT", "/api/v1/overlays/{id}"),
            ("DELETE", "/api/v1/overlays/{id}"),
            ("GET", "/api/v1/probes"),
            ("GET", "/api/v1/probes/{id}"),
            ("POST", "/api/v1/probes/{id}"),
            ("PUT", "/api/v1/probes/{id}"),
            ("DELETE", "/api/v1/probes/{id}"),
            ("POST", "/api/v1/commands/start"),
            ("POST", "/api/v1/commands/stop"),
            ("POST", "/api/v1/commands/swap"),
            ("POST", "/api/v1/commands/apply-layout"),
            ("GET", "/api/v1/alarms"),
            ("POST", "/api/v1/alarms/{id}/ack"),
            // Read-only health warnings (SA-0 / ADR-0035).
            ("GET", "/api/v1/health"),
            ("GET", "/api/v1/salvos"),
            ("GET", "/api/v1/salvos/{id}"),
            ("PUT", "/api/v1/salvos/{id}"),
            ("DELETE", "/api/v1/salvos/{id}"),
            ("POST", "/api/v1/salvos/{id}/arm"),
            ("POST", "/api/v1/salvos/{id}/take"),
            ("POST", "/api/v1/salvos/{id}/cancel"),
            // Per-stream crosspoint routing (RT-11): plan (classify) + take (apply).
            ("POST", "/api/v1/routing/plan"),
            ("POST", "/api/v1/routing/{kind}/take"),
            ("GET", "/api/v1/tally"),
            ("PUT", "/api/v1/tally/override"),
            ("DELETE", "/api/v1/tally/override"),
            ("GET", "/api/v1/tally/profiles"),
            ("GET", "/api/v1/tally/profiles/{id}"),
            ("PUT", "/api/v1/tally/profiles/{id}"),
            ("DELETE", "/api/v1/tally/profiles/{id}"),
            // WHEP focus sessions (sub-second WebRTC preview) per scope.
            ("POST", "/api/v1/preview/program/whep"),
            ("DELETE", "/api/v1/preview/program/whep/{session_id}"),
            ("POST", "/api/v1/preview/inputs/{id}/whep"),
            ("DELETE", "/api/v1/preview/inputs/{id}/whep/{session_id}"),
            ("POST", "/api/v1/preview/outputs/{id}/whep"),
            ("DELETE", "/api/v1/preview/outputs/{id}/whep/{session_id}"),
            // Read-only change audit log.
            ("GET", "/api/v1/audit"),
            // Config versioning: history + commit, single revision, diff, rollback.
            ("GET", "/api/v1/config/{target}"),
            ("PUT", "/api/v1/config/{target}"),
            ("GET", "/api/v1/config/{target}/rev/{revision}"),
            ("GET", "/api/v1/config/{target}/diff"),
            ("POST", "/api/v1/config/{target}/rollback"),
            // AsyncAPI 3.0 document (realtime/WebSocket spec, generated by xtask).
            ("GET", "/asyncapi.json"),
            // AMWA NMOS Node API (under the standardised /x-nmos base).
            ("GET", "/x-nmos/node/v1.3/self"),
            ("GET", "/x-nmos/node/v1.3/devices"),
            ("GET", "/x-nmos/node/v1.3/senders"),
            ("GET", "/x-nmos/node/v1.3/receivers"),
            (
                "GET",
                "/x-nmos/connection/v1.1/single/receivers/{id}/active",
            ),
            (
                "PATCH",
                "/x-nmos/connection/v1.1/single/receivers/{id}/staged",
            ),
            ("GET", "/api/v1/ws"),
            ("GET", "/api/v1/events"),
        ]
    }
}

/// Serve the raw `OpenAPI` document as JSON.
async fn openapi_json(State(_state): State<AppState>) -> Json<utoipa::openapi::OpenApi> {
    Json(ApiDoc::openapi())
}

/// Serve the embedded `AsyncAPI` 3.0 document as JSON.
///
/// The document is the committed output of `cargo xtask gen-asyncapi`
/// (`docs/api/asyncapi.json`), embedded at compile time. No `AppState` is
/// needed — the spec is static and carries no session-specific data.
async fn asyncapi_json() -> impl IntoResponse {
    (
        [
            (
                header::CONTENT_TYPE,
                // Serve as `application/json` rather than a vendor MIME type so
                // browsers and plain HTTP clients can consume it without special
                // Accept headers (mirrors the openapi.json convention above).
                "application/json",
            ),
            (
                header::CACHE_CONTROL,
                // The document changes only on re-deploy; `no-cache` means the
                // browser re-validates on every navigation but can serve a
                // cached copy when the ETag matches, so latency stays low.
                "no-cache",
            ),
        ],
        ASYNCAPI_JSON,
    )
}

/// Build the router serving the `OpenAPI` JSON (`/api/v1/openapi.json`), the
/// Scalar UI (`/docs`), and the `AsyncAPI` 3.0 JSON (`/asyncapi.json`).
pub fn openapi_router() -> Router<AppState> {
    Router::new()
        .route("/api/v1/openapi.json", axum::routing::get(openapi_json))
        .route("/asyncapi.json", axum::routing::get(asyncapi_json))
        .merge(Scalar::with_url("/docs", ApiDoc::openapi()))
}
